# 作者
author = "xxx"

# デバッグモードかどうか
debug = true

# Todoistセクション
[todoist]
apiToken = "c8d731afea3f6e25bc5f7257e0f8575f2199f126"  # TodoistのAPIトークン
targetProjectName = "あとで読む👀"      # URLを含むタスクの移動先プロジェクト名